name: CI

ON:
  push:
    branches:
      -main
      -deployment

jobs:
 build:
   runs-on:ubundu-latest

   steps:
    -uses: actions/checkout@v4

    -uses:actions/setup-python@v5
    with:
     python-version: "3.11"


  -run: pip install -r api/requirements.txt